#############################################################################
# Makefile for building: libfancywidgets.so
# Generated by qmake (2.01a) (Qt 4.6.2) on: wt. mar 1 21:12:25 2011
# Project:  fancy_widgets.pro
# Template: lib
# Command: /usr/bin/qmake -unix -o Makefile fancy_widgets.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_PLUGIN -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQDESIGNER_EXPORT_WIDGETS -DQT_SHARED
CFLAGS        = -pipe -O2 -D_REENTRANT -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -D_REENTRANT -Wall -W -fPIC $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtDesigner -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I. -Isrc -Irelease
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/lib/qt4 -shared
LIBS          = $(SUBLIBS)  -L/usr/lib/qt4 -lQtXml -L/usr/lib/qt4 -lQtGui -L/usr/X11R6/lib -lQtCore -lgthread-2.0 -lrt -lglib-2.0 -lQtDesigner -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = release/

####### Files

SOURCES       = src/fancy_widgets.cpp \
		src/indicator.cpp \
		src/indicator_plugin.cpp \
		src/indicatorl.cpp \
		src/indicatorl_plugin.cpp release/moc_fancy_widgets.cpp \
		release/moc_indicator.cpp \
		release/moc_indicator_plugin.cpp \
		release/moc_indicatorl.cpp \
		release/moc_indicatorl_plugin.cpp
OBJECTS       = release/fancy_widgets.o \
		release/indicator.o \
		release/indicator_plugin.o \
		release/indicatorl.o \
		release/indicatorl_plugin.o \
		release/moc_fancy_widgets.o \
		release/moc_indicator.o \
		release/moc_indicator_plugin.o \
		release/moc_indicatorl.o \
		release/moc_indicatorl_plugin.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/designer.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		fancy_widgets.pro
QMAKE_TARGET  = fancywidgets
DESTDIR       = dist/
TARGET        = libfancywidgets.so
TARGETD       = libfancywidgets.so

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile  dist/$(TARGET)

dist/$(TARGET):  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	@$(CHK_DIR_EXISTS) dist/ || $(MKDIR) dist/ 
	-$(DEL_FILE) $(TARGET)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-$(MOVE) $(TARGET) dist/



Makefile: fancy_widgets.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/designer.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/qt4/libQtXml.prl \
		/usr/lib/qt4/libQtCore.prl \
		/usr/lib/qt4/libQtGui.prl \
		/usr/lib/qt4/libQtDesigner.prl
	$(QMAKE) -unix -o Makefile fancy_widgets.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/designer.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/qt4/libQtXml.prl:
/usr/lib/qt4/libQtCore.prl:
/usr/lib/qt4/libQtGui.prl:
/usr/lib/qt4/libQtDesigner.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile fancy_widgets.pro

dist: 
	@$(CHK_DIR_EXISTS) release/fancywidgets1.0.0 || $(MKDIR) release/fancywidgets1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) release/fancywidgets1.0.0/ && $(COPY_FILE) --parents src/fancy_widgets.h src/indicator.h src/indicator_plugin.h src/indicatorl.h src/indicatorl_plugin.h release/fancywidgets1.0.0/ && $(COPY_FILE) --parents src/fancy_widgets.cpp src/indicator.cpp src/indicator_plugin.cpp src/indicatorl.cpp src/indicatorl_plugin.cpp release/fancywidgets1.0.0/ && (cd `dirname release/fancywidgets1.0.0` && $(TAR) fancywidgets1.0.0.tar fancywidgets1.0.0 && $(COMPRESS) fancywidgets1.0.0.tar) && $(MOVE) `dirname release/fancywidgets1.0.0`/fancywidgets1.0.0.tar.gz . && $(DEL_FILE) -r release/fancywidgets1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: release/moc_fancy_widgets.cpp release/moc_indicator.cpp release/moc_indicator_plugin.cpp release/moc_indicatorl.cpp release/moc_indicatorl_plugin.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) release/moc_fancy_widgets.cpp release/moc_indicator.cpp release/moc_indicator_plugin.cpp release/moc_indicatorl.cpp release/moc_indicatorl_plugin.cpp
release/moc_fancy_widgets.cpp: src/indicator_plugin.h \
		src/indicatorl_plugin.h \
		src/fancy_widgets.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/fancy_widgets.h -o release/moc_fancy_widgets.cpp

release/moc_indicator.cpp: src/indicator.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/indicator.h -o release/moc_indicator.cpp

release/moc_indicator_plugin.cpp: src/indicator_plugin.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/indicator_plugin.h -o release/moc_indicator_plugin.cpp

release/moc_indicatorl.cpp: src/indicatorl.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/indicatorl.h -o release/moc_indicatorl.cpp

release/moc_indicatorl_plugin.cpp: src/indicatorl_plugin.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/indicatorl_plugin.h -o release/moc_indicatorl_plugin.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

release/fancy_widgets.o: src/fancy_widgets.cpp src/fancy_widgets.h \
		src/indicator_plugin.h \
		src/indicatorl_plugin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/fancy_widgets.o src/fancy_widgets.cpp

release/indicator.o: src/indicator.cpp src/indicator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/indicator.o src/indicator.cpp

release/indicator_plugin.o: src/indicator_plugin.cpp src/indicator.h \
		src/indicator_plugin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/indicator_plugin.o src/indicator_plugin.cpp

release/indicatorl.o: src/indicatorl.cpp src/indicatorl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/indicatorl.o src/indicatorl.cpp

release/indicatorl_plugin.o: src/indicatorl_plugin.cpp src/indicatorl.h \
		src/indicatorl_plugin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/indicatorl_plugin.o src/indicatorl_plugin.cpp

release/moc_fancy_widgets.o: release/moc_fancy_widgets.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/moc_fancy_widgets.o release/moc_fancy_widgets.cpp

release/moc_indicator.o: release/moc_indicator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/moc_indicator.o release/moc_indicator.cpp

release/moc_indicator_plugin.o: release/moc_indicator_plugin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/moc_indicator_plugin.o release/moc_indicator_plugin.cpp

release/moc_indicatorl.o: release/moc_indicatorl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/moc_indicatorl.o release/moc_indicatorl.cpp

release/moc_indicatorl_plugin.o: release/moc_indicatorl_plugin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/moc_indicatorl_plugin.o release/moc_indicatorl_plugin.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/local/lib/ || $(MKDIR) $(INSTALL_ROOT)/usr/local/lib/ 
	-$(INSTALL_PROGRAM) "dist/$(TARGET)" "$(INSTALL_ROOT)/usr/local/lib/$(TARGET)"
	-$(STRIP) --strip-unneeded "$(INSTALL_ROOT)/usr/local/lib/$(TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/local/lib/$(TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/lib/ 


install_documentation: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/home/soldier/workspace/fancy-widgets/docs/ || $(MKDIR) $(INSTALL_ROOT)/home/soldier/workspace/fancy-widgets/docs/ 
	doxygen Doxyfile;


install:  install_target install_documentation  FORCE

uninstall: uninstall_target   FORCE

FORCE:

